version: '3.9'

services:
  template:
    build:
      context: ./../../
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "0.0.0.0:8080:5055"
      - "0.0.0.0:8081:5056"
    networks:
      - dev-network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
